name: Run clang-format Linter

on:
  push:
    paths-ignore:
      - "docs"
      - "docker"
      - ".github"
  pull_request:
    paths:
      - "docs"
      - "docker"
      - ".github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: 'src'
          exclude: 'src/rust'
          extensions: 'h,hpp,cpp,c'
          clangFormatVersion: 14
          inplace: True

      - uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}